#!/usr/bin/env python3

import argparse
parser = argparse.ArgumentParser()
parser.add_argument('-w', '--words', type=int, default=4,) #words
parser.add_argument('-c', '--caps', type=int, default=0,) #caps
parser.add_argument('-n', '--numbers', type=int, default=0,) #numbers
parser.add_argument('-s', '--symbols', type=int, default=0,) #symbols 
args = parser.parse_args()
import random

#defult:
def r=RandomWord():
    lines = open('words.txt').read().splitlines()
    return random.choice(lines)

#for words method:
def InsertRand(str, insert):
    randomIndex = random.randint(0, len(str))
    return str[0:randomIndex] + insert + str[randomIndex:]

#for caps method:
words = []
for x in range(0, args.words):
    if (args.caps > 0):
        words.append(RandomWord().capitalize())
        args.caps -= 1
    else:
        words.append(RandomWord())

password = ""
for x in range(0, args.words):
    w = random.choice(words)
    words.remove(w)
    password += w

#for symbols method:
while args.symbols > 0:
    s = random.choice(["~","!","@","#","$","&","^","%","*",".",";",":"])
    password = InsertRand(password, s)
    args.symbols -= 1

#for numbers method:
while args.numbers > 0:
    d = random.choice(["0","1","2","3","4","5","6","7","8","9"])
    password = InsertRand(password, d)
    args.numbers -= 1

#FINAL PRINT!!
print(password)
