#!/usr/bin/env python3
import argparse
import random

parser = argparse.ArgumentParser()
parser.add_argument('-w', '--words', type=int, default=4,)
parser.add_argument('-c', '--caps', type=int, default=0,)
parser.add_argument('-n', '--numbers', type=int, default=0,)
parser.add_argument('-s', '--symbols', type=int, default=0,)
args = parser.parse_args()

def randomWord():
    lines = open('words.txt').read().splitlines()
    return random.choice(lines)

def insertRand(str, insert):
    randomIndex = random.randint(0, len(str))
    return str[0:randomIndex] + insert + str[randomIndex:]

words = []
for i in range(0, args.words):
    if (args.caps > 0):
        words.append(randomWord().capitalize())
        args.caps -= 1
    else:
        words.append(randomWord())

password = ""
for i in range(0, args.words):
    w = random.choice(words)
    words.remove(w)
    password += w

while args.symbols > 0:
    s = random.choice(["~","!","@","#","$","&","^","%","*",".",";",":"])
    password = insertRand(password, s)
    args.symbols -= 1

while args.numbers > 0:
    d = random.choice(["0","1","2","3","4","5","6","7","8","9"])
    password = insertRand(password, d)
    args.numbers -= 1

print(password)
